### ISSUE TITLE
Bullet Damage Error

### ISSUE THREAD

**Issue by nonatus** [TruthfullyHonest/ScpMessages#1]
![image](https://user-images.githubusercontent.com/81320094/126198559-bcb9c118-1b14-4341-b405-a145faed66bf.png)

**Comment by HonestResolv3** [comment]
Looks like its coming from the 2nd message line [here](https://github.com/HonestResolv3/ScpMessages/blob/main/ScpMessages/ScpMessages/EventHandlers.cs#L308)

Will add a fix ASAP

**Comment by HonestResolv3** [comment]
Fixed, still checking on the new SCP damage messages but humans when they get shot display messages for both users now. I also did some formatting fixes for the player names
